stages:
  - test
  - deploy

test-backend:
  image: golang:1.23-alpine
  stage: test
  script:
    - cd backend && go test ./...
  tags:
    - docker

deploy:
  image: ubuntu:latest
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y openssh-client rsync
    - eval $(ssh-agent -s)
    - chmod 600 $SSH_PRIVATE_KEY
    - ssh-add $SSH_PRIVATE_KEY
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile /dev/null" > ~/.ssh/config
  script:
    - rsync -avz --exclude='.git' --exclude='.env' ./ root@10.93.27.23:/opt/lamba/
    - ssh root@10.93.27.23 "
        cd /opt/lamba &&
        docker compose down &&
        docker compose up -d --build
      "
  only:
    - main
  tags:
    - docker
  environment:
    name: production